### ISSUE TITLE
Red Hydrogen One plays 3d MPV with your program for only 20 seconds?

### ISSUE THREAD

**Issue by lde3d** [jakedowns/mpv-android#1]
For whatever reason, when I try to play a SBS film with your program, it works beautifully, but the program ends in 15 to 20 seconds.  Am I doing something wrong?

ldelie@comcast.net

**Comment by jakedowns** [comment]
@Ide3d 

hey there, sorry, just seeing this.

i just released an updated build, maybe you could try uninstalling and installing the new .apk

https://github.com/jakedowns/mpv-android/releases/tag/mpv-4v-2022-05-18-litbyleiabeta

it might be something to do with the way your video is being streamed or the way it is encoded

have you tried multiple files?

how are you accessing them, are they stored locally on the phone, or streaming via Jellyfin or Emby?

i've been able to watch full films using MPV + Jellyfin streaming

it might be your local network perhaps? maybe try lowering the streaming encoding bitrate quality settings?

shot in the dark: try again with all other apps closed / after restarting the phone.

Hope this helps. Let me know if you need any more assistance.

**Comment by lde3d** [comment]
I figured it out.  You can't use too large of a file; may be a bitrate issue.  I re-encoded some files smaller and it works fine now.  Just not a full 3D Blu-Ray at max resolution.

 

 

Larry

**Comment by jakedowns** [comment]
glad to hear. hope you enjoy! if you missed it, the new version can play O/U T/B files
